USE ECOMMERCE_DW.BRONZE;

CREATE OR REPLACE FILE FORMAT BRONZE_CSV_FORMAT
    TYPE = CSV,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    PARSE_HEADER = TRUE;
  
-- LOAD USERS
COPY INTO USERS
FROM @BRONZE_STAGE/user_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD SELLERS
COPY INTO SELLERS
FROM @BRONZE_STAGE/seller_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD PRODUCTS
COPY INTO PRODUCTS
FROM @BRONZE_STAGE/products_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD ORDERS
COPY INTO ORDERS
FROM @BRONZE_STAGE/order_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD ORDER ITEMS
COPY INTO ORDER_ITEMS
FROM @BRONZE_STAGE/order_item_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD PAYMENTS
COPY INTO PAYMENTS
FROM @BRONZE_STAGE/payment_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- LOAD FEEDBACK
COPY INTO FEEDBACK
FROM @BRONZE_STAGE/feedback_dataset.csv
FILE_FORMAT = (FORMAT_NAME = 'BRONZE_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVEA
