CREATE OR REPLACE DATABASE ecommerce_dw;

CREATE OR REPLACE SCHEMA ecommerce_dw.bronze;
CREATE OR REPLACE SCHEMA ecommerce_dw.silver;
CREATE OR REPLACE SCHEMA ecommerce_dw.gold;

USE ECOMMERCE_DW.BRONZE;

CREATE OR REPLACE STAGE BRONZE_STAGE;

-- ORDERS
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR,
    USER_NAME VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_DATE TIMESTAMP_NTZ,
    ORDER_APPROVED_DATE TIMESTAMP_NTZ,
    PICKUP_DATE TIMESTAMP_NTZ,
    DELIVERED_DATE TIMESTAMP_NTZ,
    ESTIMATED_TIME_DELIVERY TIMESTAMP_NTZ
);

-- ORDER_ITEMS
CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ID VARCHAR,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID VARCHAR,
    SELLER_ID VARCHAR,
    PICKUP_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(38,12),
    SHIPPING_COST NUMBER(38,12)
);

-- USERS
CREATE OR REPLACE TABLE USERS (
    USER_NAME VARCHAR,
    CUSTOMER_ZIP_CODE NUMBER,
    CUSTOMER_CITY VARCHAR,
    CUSTOMER_STATE VARCHAR
);

-- SELLERS
CREATE OR REPLACE TABLE SELLERS (
    SELLER_ID VARCHAR,
    SELLER_ZIP_CODE NUMBER,
    SELLER_CITY VARCHAR,
    SELLER_STATE VARCHAR
);

-- PRODUCTS
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_CATEGORY VARCHAR,
    PRODUCT_NAME_LENGHT NUMBER(38,1),
    PRODUCT_DESCRIPTION_LENGHT NUMBER(38,1),
    PRODUCT_PHOTOS_QTY NUMBER(38,1),
    PRODUCT_WEIGHT_G NUMBER(38,1),
    PRODUCT_LENGTH_CM NUMBER(38,1),
    PRODUCT_HEIGHT_CM NUMBER(38,1),
    PRODUCT_WIDTH_CM NUMBER(38,1)
);

-- PAYMENTS
CREATE OR REPLACE TABLE PAYMENTS (
    ORDER_ID VARCHAR,
    PAYMENT_SEQUENTIAL NUMBER,
    PAYMENT_TYPE VARCHAR,
    PAYMENT_INSTALLMENTS NUMBER,
    PAYMENT_VALUE NUMBER(38,13)
);

-- FEEDBACK
CREATE OR REPLACE TABLE FEEDBACK (
    FEEDBACK_ID VARCHAR,
    ORDER_ID VARCHAR,
    FEEDBACK_SCORE NUMBER,
    FEEDBACK_FORM_SENT_DATE TIMESTAMP_NTZ,
    FEEDBACK_ANSWER_DATE TIMESTAMP_NTZ
);
